-- v2_test_keywords 백업 (2025-08-07T08:47:28.485Z)
-- 총 46개 레코드

-- 복구 시 사용:
-- DELETE FROM v2_test_keywords; -- 주의: 기존 데이터 삭제
-- 아래 INSERT문들 실행

INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (16, '노트북', '8429938998', 'test', true, 4, 0, 0, '{"ljc_allow":[],"mercury_allow":["script","stylesheet"],"front_cdn_allow":["script"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":["*.gif","*.mp4"]}'::jsonb, '2025-08-06T10:38:09.638Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (17, '노트북게이밍', '8898509721', 'test', true, 4, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":["*"],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T10:38:09.638Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (18, '노트북업무용', '6662026640', 'test', true, 4, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T10:38:09.638Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (19, '먼지안나는 무표백 화장지', '8230612304', NULL, true, 0, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","xhr","fetch"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:28:10.513Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (20, '먼지안나는 천연펄프 키친타올', '8926865358', 'test1', true, 17, 8, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":["*"],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:28:10.534Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (21, '먼지안나는 무표백 화장지', '8230612304', 'test1', true, 17, 8, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:28:10.542Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (22, '냉동 스위트 아이스 망고', '7281361752', 'test2', true, 18, 9, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:28:10.549Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (23, '먼지안나는 무표백 화장지', '8230612304', 'test1', true, 28, 11, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:28:10.557Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (24, '먼지안나는 천연펄프 키친타올', '8926865358', 'test1', true, 28, 11, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:28:10.565Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (25, '비룸 청소기 전용 전원 아답터', '8538335345', 'u22', true, 80, 2, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":["*"],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.356Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (26, '비룸 무선청소기 퓨어라이트 먼지통', '8538331060', 'u22', true, 81, 1, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.377Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (27, '비룸 23000 V9-B1 청소기 먼지통 교체', '8538331060', 'u22', true, 80, 1, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.385Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (28, '비룸 청소기 분리형 먼지통 부품', '8538331060', 'u22', true, 81, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.393Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (29, '비룸 퓨어라이트 청소기 수거통', '8538331060', 'u22', true, 81, 1, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.400Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (30, '비룸 무선청소기 투명 먼지통 리필', '8538331060', 'u24', true, 100, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.408Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (31, '비룸 청소기 호환 먼지통 부속품', '8538331060', 'u24', true, 100, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.415Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (32, '비룸 무선청소기 퓨어라이트 연장봉', '8538330663', 'u24', true, 99, 1, 0, '{"ljc_allow":["*"],"mercury_allow":[],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.424Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (33, '퓨어라이트 비룸 연장봉 무선청소기', '8538330663', 'u24', true, 100, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.431Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (34, '퓨어라이트 비룸 연장봉', '8538330663', 'u24', true, 100, 0, 0, '{"ljc_allow":[],"mercury_allow":["*"],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.438Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (35, '퓨어라이트 비룸 연장봉 b1', '8538330663', 'vm-win11', true, 88, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":["*"],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.446Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (36, '비룸 퓨어라이트 연장봉', '8538330663', 'vm-win11', true, 88, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.453Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (37, '퓨어라이트 비룸 연장봉 v9', '8538330663', 'vm-win11', true, 87, 1, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.461Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (38, '비룸 무선청소기 퓨어라이트 헤파필터', '8575068479', 'vm-win11', true, 78, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.467Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (39, '비룸 23000 V9-B1 청소기 필터 헤파', '8575068479', 'vm-win11', true, 77, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":["*"],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.473Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (40, '비룸 청소기 정품 헤파필터', '8575068479', 'vm-no4', true, 72, 2, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["script","stylesheet"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.481Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (41, '비룸 무선청소기 필터 부품', '8575068479', 'vm-no4', true, 75, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.488Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (42, '비룸 청소기 호환 필터 리필', '8575068479', 'vm-no4', true, 49, 24, 0, '{"ljc_allow":["*"],"mercury_allow":[],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.496Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (43, '비룸 헤파필터', '8575068479', 'vm-no4', true, 74, 1, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.504Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (44, '비룸 무선청소기 충전기 부품', '8538335345', 'vm-no4', true, 75, 0, 0, '{"ljc_allow":[],"mercury_allow":["*"],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.512Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (45, '비룸 퓨어라이트 청소기 충전 어댑터', '8538335345', 'vm-r10', true, 61, 1, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":["*"],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.519Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (46, '비룸 23000 V9-B1 배터리 연결잭', '8538335345', 'vm-r10', true, 64, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.527Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (47, '비룸 청소기 전용 전원 충전기', '8538335345', 'vm-r10', true, 61, 2, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":["*"],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.533Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (48, '비룸 청소기 먼지 수거통 정품', '8538331060', 'vm-r10', true, 63, 1, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":["*"],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.540Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (49, '비룸 퓨어라이트 먼지필터통 - 중복', '8538331060', 'vm-r10', true, 64, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.547Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (50, '비룸 무선청소기 리필형 먼지통', '8538331060', 'u24', true, 13, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","xhr","fetch"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.555Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (51, '비룸 청소기 전용 먼지 분리통', '8538331060', 'u24', true, 13, 0, 0, '{"ljc_allow":["*"],"mercury_allow":["*"],"front_cdn_allow":[],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.562Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (52, '연장봉 비룸 퓨어라이트 무선청소기 23000 V9-B1', '8538330663', 'u24', true, 13, 0, 0, '{"ljc_allow":["*"],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","script","fetch"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.570Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (53, '연장봉 비룸 퓨어라이트 23000 V9-B1', '8538330663', 'u24', true, 13, 0, 0, '{"ljc_allow":[],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","script"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T12:36:47.577Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (54, '청소기 비룸 전용 전원 아답터', '8538335345', 'u24', false, 13, 0, 0, '{"ljc_allow":["*"],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","script","xhr"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.941Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (55, '무선청소기 비룸 퓨어라이트 먼지통', '8538331060', 'u22', false, 26, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","xhr"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.963Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (56, '23000 비룸 V9-B1 청소기 먼지통 교체', '8538331060', 'u22', false, 26, 0, 0, '{"ljc_allow":[],"mercury_allow":["*"],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","xhr"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.970Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (57, '청소기 비룸 분리형 먼지통 부품', '8538331060', 'u22', false, 26, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":["*"],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","fetch"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.976Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (58, '퓨어라이트 비룸 청소기 수거통', '8538331060', 'u22', false, 26, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":["*"],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["document","fetch"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.984Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (59, '무선청소기 비룸 투명 먼지통 리필', '8538331060', 'u22', false, 26, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":["*"],"static_cdn_allow":[],"coupang_main_allow":["document","fetch"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.990Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (60, '청소기 비룸 호환 먼지통 부속품', '8538331060', 'vm-win11', false, 7, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":["*"],"coupang_main_allow":["*"],"thumbnail_cdn_allow":[],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:27.998Z', NULL);
INSERT INTO v2_test_keywords (id, keyword, product_code, agent, cart_click_enabled, success_count, fail_count, total_blocks, optimization_config, created_at, updated_at) VALUES (61, '무선청소기 비룸 퓨어라이트 연장봉', '8538330663', 'vm-win11', false, 7, 0, 0, '{"ljc_allow":[],"mercury_allow":[],"front_cdn_allow":["*"],"image_cdn_allow":[],"img1a_cdn_allow":[],"assets_cdn_allow":[],"static_cdn_allow":[],"coupang_main_allow":["*"],"thumbnail_cdn_allow":["*"],"coupang_main_block_patterns":[]}'::jsonb, '2025-08-06T14:37:28.004Z', NULL);
